---
title: "temp_tests_rmd_html"
author: "sdfg"
date: "28 11 2022"
output: html_document
---


# Input Files INT

asdf


```{r setup}

devtools::load_all()

knitr::knit_engines$set(sparql = eng_sparql)

```



```{r results="asis"}

  query <- "PREFIX schema: <http://schema.org/>
  PREFIX cube: <https://cube.link/>
  SELECT * 
  FROM <https://lindas.admin.ch/stadtzuerich/stat>
  WHERE {
    ?sub a cube:Cube ;
      schema:name ?label ;
  }"
  
  # Anzahl CubeIDs x Labels, IDs und Labels
  cubes <- sparql2df("https://int.lindas.admin.ch/query/", query)

print(cubes)

```


```{r}
authenticate <- httr::authenticate(user = Sys.getenv("SSZ_VIEWS_USER"),
																	 password = Sys.getenv("SSZ_VIEWS_PW"))


# This query needs authentication
endpoint_b <- "https://stardog.cluster.ldbar.ch/ssz-views"
query_b <- "PREFIX cube: <https://cube.link/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?cube (COUNT(?observation) AS ?count)
FROM <https://lindas.admin.ch/stadtzuerich/stat>
WHERE {
  ?cube a cube:Cube ;
    cube:observationSet/cube:observation ?observation .
} GROUP BY ?cube ORDER BY ?count"


result_b_auth <- sparql2df(endpoint_b, query_b, auth = authenticate)
# result_b_auth has 1 variable with 1363 obs.
print(result_b_auth)


```


